### ISSUE TITLE
Costa Rica

### ISSUE THREAD

**Issue by Caballero-Arepa** [Caballero-Arepa/Latin-American_Civs#30]
Progress:

> Code:
- [x] Nation profile
- [x] UB Ecoturistic Hotel
- [x] UU Campesino Patriota
- [x] UB San José theatre
- [x] UB Pineapple Plantation

> Icons:
- [x] Civ
- [x] UB Ecoturistic Hotel
- [x] UU Campesino Patriota
- [x] UB San José theatre (3&4)
- [x] UB Pineapple Plantation (3&4)

> Sprites:
- [x] Campesino

> Music:
- [ ] Theme

**Comment by ArchDuque-Pancake** [comment]
Ideas:
Una unidad como Levies pero con machete
Reserva Natural
Turismo ecologico

**Comment by ArchDuque-Pancake** [comment]
Code for the buildings for 3&4:

> San José theatre

> Pineapple Plantation

**Comment by Nana190368** [comment]
{
		"name": "Teatro Nacional",
		"replaces": "Circus Maximus",
		"isNationalWonder": true,
		"cost": 300,
		"requiredTech": "Architecture",
		"culture": 1,
		"happiness": 5,		
	   "uniqueTo": "Costa Rica",
		"uniques": ["Requires a [Theatre] in all cities","Empire enters golden age", "[+5 Gold] from every [Theatre]"],
