### ISSUE TITLE
Missing Sprites

### ISSUE THREAD

**Issue by Caballero-Arepa** [Caballero-Arepa/Latin-American_Civs#36]
>  Vigilance Post of Salvador
>  Jungla
>  Mixed Milicia
>  Campesino Patriota

Me ofrezco a hacer los sprites de los anteriores puntos, tal como hice con el chigüiro. Los haré para fantasy hex y hexarealm aparte voy a remodelar los chigüiros.

_Originally posted by @CPlayxs in https://github.com/Caballero-Arepa/Latin-American_Civs/issues/16#issuecomment-1207267574_

**Comment by CPlayxs** [comment]
Hecho

**Comment by Caballero-Arepa** [comment]
Jeje perdona, faltan otros más que no había puesto:

- Buccaneer de Panamá
- Fuerza Pública de Panamá
- Guerrillero de Cuba
