### ISSUE TITLE
Unable to Build Broadcast Tower as Brazil. 

### ISSUE THREAD

**Issue by wviana** [Caballero-Arepa/Latin-American_Civs#39]
As in Brazil the theater is replaced by Sambodrame, looks like the Broadcast Tower is not recognizing it as replacement. 

So there is no way to build theater in Brasil, just Sambodrame. Broadcast Tower requires theater.

**Comment by wviana** [comment]
Sorry. My bad. It works. Just didn't researched it. Think Sambodrame replaces other building.

**Comment by Caballero-Arepa** [comment]
Ah jeje.
Glad its not a bug, but if it actually was, it would have been a base game problem and not mod's problem.
