### ISSUE TITLE
translation of Simplified Chinese

### ISSUE THREAD

**Issue by AutumnPizazz** [Caballero-Arepa/Latin-American_Civs#53]
I have finished the translation of Simplified Chinese for this mod. Can you give me permission to upload files？

**Comment by Caballero-Arepa** [comment]
Of course, you are free to upload your files my friend.

**Comment by AutumnPizazz** [comment]
Well, but I have no push access to this repository.QAQ

**Comment by Caballero-Arepa** [comment]
Create a "Fork".

Then upload your translation in the fork.

After that, click on compare and Create a Pull Request

**Comment by Caballero-Arepa** [comment]
![Screenshot_20230513-225741_Brave.jpg](https://github.com/Caballero-Arepa/Latin-American_Civs/assets/78449553/214e6871-3a4d-4c04-8869-3706c8235a27)

**Comment by AutumnPizazz** [comment]
I cannot find it (I am just a Chinese student with my poor English and poor experience in github). Shall I send the file to your email and then you upload it? Many players in China wish that the mod support Chinese.

**Comment by Caballero-Arepa** [comment]
Are you on mobile?

If yes, rotate your phone horizontally, and You'll see the button.

**Comment by Caballero-Arepa** [comment]
If you still can't paste the file here.

**Comment by AutumnPizazz** [comment]
File of 'json' cannot be upload so I edit it as 'txt' and upload it here.
[Simplified_Chinese.txt](https://github.com/Caballero-Arepa/Latin-American_Civs/files/11471108/Simplified_Chinese.txt)

**Comment by Caballero-Arepa** [comment]
Alright thank you.

**Comment by Caballero-Arepa** [comment]
Alright, they are in.
