### ISSUE TITLE
Russian translation of the mod

### ISSUE THREAD

**Issue by lai55ez-faire** [Caballero-Arepa/Latin-American_Civs#62]
Greetings. I'd like to make a Russian translation of Latin-American_Civs. Could you please give me a template?

**Comment by Caballero-Arepa** [comment]
Saludos! Of course, you are welcome, give me a minute

**Comment by Caballero-Arepa** [comment]
Alr, here you go https://github.com/Caballero-Arepa/Latin-American_Civs/blob/master/jsons/translations/Russian.properties @lai55ez-faire

**Comment by lai55ez-faire** [comment]
Thank you!
