### ISSUE TITLE
Cuba Rework

### ISSUE THREAD

**Issue by Caballero-Arepa** [Caballero-Arepa/Latin-American_Civs#68]
I have linked the development branches for both mods.
The local one is called "Cuba-v2", and the other is [the master branched in the 3&4th mod's fork](https://github.com/EmperorPinguin/3rd-and-4th-Unique-Component/pull/29)

Idea for the 3&4th Unique Component mod
```
{
        "name": "Ingenio Azucarero",
        "Replaces": "Windmill",
        "uniqueTo": "Cuba",
        "gold": 2,
     "specialistSlots": {"Merchant": 1},
        "hurryCostModifier": 25,
        "percentStatBonus": {"gold": 10},
        "maintenance": 1,
        "uniques": ["Must not be on [Tundra, Snow]" ],
        "requiredTech": "Economics"
    },
```
Idea to replace the Torcedores, which in turn will go to the 3&4th unique mod
```
{
        "name": "Clínica",
        "replaces": "Hospital",
        "uniqueTo": "Cuba",
        "food": 2,
        "maintenance": 0,
        "cost": 290,
        "hurryCostModifier": 0,
        "requiredTech": "Biology"
        "uniques": ["All newly-trained [relevant] units [in this city] receive the [Medic] promotion"],
    },
```

**Comment by RealBamboolord** [comment]
Two UBs and no UU? You should rather move one of them to 3rd and 4th components and get a UU. (Just my personal opinion, not meant offensively. It's your mod after all)

**Comment by Caballero-Arepa** [comment]
> Two UBs and no UU? You should rather move one of them to 3rd and 4th components and get a UU. (Just my personal opinion, not meant offensively. It's your mod after all)

Ah yes, I'm sorry that I did not specify in the post (I didn't expect for someone to look xD)

Yes, the "Clínica" is going to replace the current "torcedores", and both the Torcedores and the Sugarcane building will go to the 3&4th unique mod, while the Guerrillero stays in the mod.
